/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard'],
  rules: {
    'selector-pseudo-class-no-unknown': [
      true,
      {
        ignorePseudoClasses: ['global'],
      },
    ],
  },
  ignoreFiles: ['**/node_modules/**', '**/dist/**', '**/build/**', '**/public/**'],
  // src/index.css is generated by the shadcn registry (design tokens, Tailwind v4 at-rules): keep
  // the registry output byte-for-byte and relax the cosmetic/notation rules that clash with it.
  overrides: [
    {
      files: ['src/index.css'],
      rules: {
        'import-notation': null,
        'lightness-notation': null,
        'hue-degree-notation': null,
        'rule-empty-line-before': null,
        'at-rule-no-unknown': null,
      },
    },
  ],
};
