/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AppointmentResponse } from '../../models/appointmentResponse';
import type { ChangeAppointmentStatusRequest } from '../../models/changeAppointmentStatusRequest';
import type { CreateAppointmentRequest } from '../../models/createAppointmentRequest';
import type { UpdateAppointmentRequest } from '../../models/updateAppointmentRequest';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List office appointments
 */
export const list2 = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<AppointmentResponse[]>(
    { url: `/api/v1/offices/${officeId}/appointments`, method: 'GET', signal },
    options,
  );
};

export const getList2MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof list2>>, TError, { officeId: string }, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof list2>>, TError, { officeId: string }, TContext> => {
  const mutationKey = ['list2'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof list2>>, { officeId: string }> = (props) => {
    const { officeId } = props ?? {};

    return list2(officeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type List2MutationResult = NonNullable<Awaited<ReturnType<typeof list2>>>;

export type List2MutationError = unknown;

/**
 * @summary List office appointments
 */
export const useList2 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof list2>>, TError, { officeId: string }, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof list2>>, TError, { officeId: string }, TContext> => {
  return useMutation(getList2MutationOptions(options), queryClient);
};
/**
 * @summary Book an appointment
 */
export const create1 = (
  officeId: string,
  createAppointmentRequest: CreateAppointmentRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<AppointmentResponse>(
    {
      url: `/api/v1/offices/${officeId}/appointments`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createAppointmentRequest,
      signal,
    },
    options,
  );
};

export const getCreate1QueryKey = (officeId: string, createAppointmentRequest?: CreateAppointmentRequest) => {
  return ['POST', 'api', 'v1', 'offices', officeId, 'appointments', createAppointmentRequest] as const;
};

export const getCreate1QueryOptions = <TData = Awaited<ReturnType<typeof create1>>, TError = unknown>(
  officeId: string,
  createAppointmentRequest: CreateAppointmentRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof create1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCreate1QueryKey(officeId, createAppointmentRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof create1>>> = ({ signal }) =>
    create1(officeId, createAppointmentRequest, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof create1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type Create1QueryResult = NonNullable<Awaited<ReturnType<typeof create1>>>;
export type Create1QueryError = unknown;

export function useCreate1<TData = Awaited<ReturnType<typeof create1>>, TError = unknown>(
  officeId: string,
  createAppointmentRequest: CreateAppointmentRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof create1>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof create1>>, TError, Awaited<ReturnType<typeof create1>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreate1<TData = Awaited<ReturnType<typeof create1>>, TError = unknown>(
  officeId: string,
  createAppointmentRequest: CreateAppointmentRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof create1>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof create1>>, TError, Awaited<ReturnType<typeof create1>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreate1<TData = Awaited<ReturnType<typeof create1>>, TError = unknown>(
  officeId: string,
  createAppointmentRequest: CreateAppointmentRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof create1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Book an appointment
 */

export function useCreate1<TData = Awaited<ReturnType<typeof create1>>, TError = unknown>(
  officeId: string,
  createAppointmentRequest: CreateAppointmentRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof create1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCreate1QueryOptions(officeId, createAppointmentRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Cancel an appointment
 */
export const cancel = (
  officeId: string,
  appointmentId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    { url: `/api/v1/offices/${officeId}/appointments/${appointmentId}`, method: 'DELETE', signal },
    options,
  );
};

export const getCancelQueryKey = (officeId: string, appointmentId: string) => {
  return ['DELETE', 'api', 'v1', 'offices', officeId, 'appointments', appointmentId] as const;
};

export const getCancelQueryOptions = <TData = Awaited<ReturnType<typeof cancel>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof cancel>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCancelQueryKey(officeId, appointmentId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof cancel>>> = ({ signal }) =>
    cancel(officeId, appointmentId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && appointmentId !== null && appointmentId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof cancel>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type CancelQueryResult = NonNullable<Awaited<ReturnType<typeof cancel>>>;
export type CancelQueryError = unknown;

export function useCancel<TData = Awaited<ReturnType<typeof cancel>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof cancel>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof cancel>>, TError, Awaited<ReturnType<typeof cancel>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCancel<TData = Awaited<ReturnType<typeof cancel>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof cancel>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof cancel>>, TError, Awaited<ReturnType<typeof cancel>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCancel<TData = Awaited<ReturnType<typeof cancel>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof cancel>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Cancel an appointment
 */

export function useCancel<TData = Awaited<ReturnType<typeof cancel>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof cancel>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCancelQueryOptions(officeId, appointmentId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Update / reschedule an appointment
 */
export const update1 = (
  officeId: string,
  appointmentId: string,
  updateAppointmentRequest: UpdateAppointmentRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<AppointmentResponse>(
    {
      url: `/api/v1/offices/${officeId}/appointments/${appointmentId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateAppointmentRequest,
      signal,
    },
    options,
  );
};

export const getUpdate1QueryKey = (
  officeId: string,
  appointmentId: string,
  updateAppointmentRequest?: UpdateAppointmentRequest,
) => {
  return ['PATCH', 'api', 'v1', 'offices', officeId, 'appointments', appointmentId, updateAppointmentRequest] as const;
};

export const getUpdate1QueryOptions = <TData = Awaited<ReturnType<typeof update1>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  updateAppointmentRequest: UpdateAppointmentRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof update1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUpdate1QueryKey(officeId, appointmentId, updateAppointmentRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof update1>>> = ({ signal }) =>
    update1(officeId, appointmentId, updateAppointmentRequest, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && appointmentId !== null && appointmentId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof update1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type Update1QueryResult = NonNullable<Awaited<ReturnType<typeof update1>>>;
export type Update1QueryError = unknown;

export function useUpdate1<TData = Awaited<ReturnType<typeof update1>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  updateAppointmentRequest: UpdateAppointmentRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof update1>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof update1>>, TError, Awaited<ReturnType<typeof update1>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdate1<TData = Awaited<ReturnType<typeof update1>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  updateAppointmentRequest: UpdateAppointmentRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof update1>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof update1>>, TError, Awaited<ReturnType<typeof update1>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdate1<TData = Awaited<ReturnType<typeof update1>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  updateAppointmentRequest: UpdateAppointmentRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof update1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update / reschedule an appointment
 */

export function useUpdate1<TData = Awaited<ReturnType<typeof update1>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  updateAppointmentRequest: UpdateAppointmentRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof update1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUpdate1QueryOptions(officeId, appointmentId, updateAppointmentRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Transition an appointment to a new status
 */
export const transition = (
  officeId: string,
  appointmentId: string,
  changeAppointmentStatusRequest: ChangeAppointmentStatusRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<AppointmentResponse>(
    {
      url: `/api/v1/offices/${officeId}/appointments/${appointmentId}/status`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: changeAppointmentStatusRequest,
      signal,
    },
    options,
  );
};

export const getTransitionQueryKey = (
  officeId: string,
  appointmentId: string,
  changeAppointmentStatusRequest?: ChangeAppointmentStatusRequest,
) => {
  return [
    'PATCH',
    'api',
    'v1',
    'offices',
    officeId,
    'appointments',
    appointmentId,
    'status',
    changeAppointmentStatusRequest,
  ] as const;
};

export const getTransitionQueryOptions = <TData = Awaited<ReturnType<typeof transition>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  changeAppointmentStatusRequest: ChangeAppointmentStatusRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof transition>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTransitionQueryKey(officeId, appointmentId, changeAppointmentStatusRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof transition>>> = ({ signal }) =>
    transition(officeId, appointmentId, changeAppointmentStatusRequest, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && appointmentId !== null && appointmentId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof transition>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type TransitionQueryResult = NonNullable<Awaited<ReturnType<typeof transition>>>;
export type TransitionQueryError = unknown;

export function useTransition<TData = Awaited<ReturnType<typeof transition>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  changeAppointmentStatusRequest: ChangeAppointmentStatusRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof transition>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof transition>>,
          TError,
          Awaited<ReturnType<typeof transition>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTransition<TData = Awaited<ReturnType<typeof transition>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  changeAppointmentStatusRequest: ChangeAppointmentStatusRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof transition>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof transition>>,
          TError,
          Awaited<ReturnType<typeof transition>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTransition<TData = Awaited<ReturnType<typeof transition>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  changeAppointmentStatusRequest: ChangeAppointmentStatusRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof transition>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Transition an appointment to a new status
 */

export function useTransition<TData = Awaited<ReturnType<typeof transition>>, TError = unknown>(
  officeId: string,
  appointmentId: string,
  changeAppointmentStatusRequest: ChangeAppointmentStatusRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof transition>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTransitionQueryOptions(officeId, appointmentId, changeAppointmentStatusRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
