/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AppointmentResponse } from '../../models/appointmentResponse';
import type { ChangeAppointmentStatusRequest } from '../../models/changeAppointmentStatusRequest';
import type { CreateAppointmentRequest } from '../../models/createAppointmentRequest';
import type { UpdateAppointmentRequest } from '../../models/updateAppointmentRequest';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List office appointments
 */
export const list2 = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<AppointmentResponse[]>(
    { url: `/api/v1/offices/${officeId}/appointments`, method: 'GET', signal },
    options,
  );
};

export const getList2QueryKey = (officeId: string) => {
  return ['api', 'v1', 'offices', officeId, 'appointments'] as const;
};

export const getList2QueryOptions = <TData = Awaited<ReturnType<typeof list2>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getList2QueryKey(officeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof list2>>> = ({ signal }) =>
    list2(officeId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type List2QueryResult = NonNullable<Awaited<ReturnType<typeof list2>>>;
export type List2QueryError = unknown;

export function useList2<TData = Awaited<ReturnType<typeof list2>>, TError = unknown>(
  officeId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof list2>>, TError, Awaited<ReturnType<typeof list2>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList2<TData = Awaited<ReturnType<typeof list2>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof list2>>, TError, Awaited<ReturnType<typeof list2>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList2<TData = Awaited<ReturnType<typeof list2>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List office appointments
 */

export function useList2<TData = Awaited<ReturnType<typeof list2>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list2>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getList2QueryOptions(officeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Book an appointment
 */
export const create1 = (
  officeId: string,
  createAppointmentRequest: CreateAppointmentRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<AppointmentResponse>(
    {
      url: `/api/v1/offices/${officeId}/appointments`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createAppointmentRequest,
      signal,
    },
    options,
  );
};

export const getCreate1MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create1>>,
    TError,
    { officeId: string; data: CreateAppointmentRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { officeId: string; data: CreateAppointmentRequest },
  TContext
> => {
  const mutationKey = ['create1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create1>>,
    { officeId: string; data: CreateAppointmentRequest }
  > = (props) => {
    const { officeId, data } = props ?? {};

    return create1(officeId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Create1MutationResult = NonNullable<Awaited<ReturnType<typeof create1>>>;
export type Create1MutationBody = CreateAppointmentRequest;
export type Create1MutationError = unknown;

/**
 * @summary Book an appointment
 */
export const useCreate1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create1>>,
      TError,
      { officeId: string; data: CreateAppointmentRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create1>>,
  TError,
  { officeId: string; data: CreateAppointmentRequest },
  TContext
> => {
  return useMutation(getCreate1MutationOptions(options), queryClient);
};
/**
 * @summary Cancel an appointment
 */
export const cancel = (
  officeId: string,
  appointmentId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    { url: `/api/v1/offices/${officeId}/appointments/${appointmentId}`, method: 'DELETE', signal },
    options,
  );
};

export const getCancelMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancel>>,
    TError,
    { officeId: string; appointmentId: string },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancel>>,
  TError,
  { officeId: string; appointmentId: string },
  TContext
> => {
  const mutationKey = ['cancel'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancel>>,
    { officeId: string; appointmentId: string }
  > = (props) => {
    const { officeId, appointmentId } = props ?? {};

    return cancel(officeId, appointmentId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelMutationResult = NonNullable<Awaited<ReturnType<typeof cancel>>>;

export type CancelMutationError = unknown;

/**
 * @summary Cancel an appointment
 */
export const useCancel = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancel>>,
      TError,
      { officeId: string; appointmentId: string },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancel>>,
  TError,
  { officeId: string; appointmentId: string },
  TContext
> => {
  return useMutation(getCancelMutationOptions(options), queryClient);
};
/**
 * @summary Update / reschedule an appointment
 */
export const update1 = (
  officeId: string,
  appointmentId: string,
  updateAppointmentRequest: UpdateAppointmentRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<AppointmentResponse>(
    {
      url: `/api/v1/offices/${officeId}/appointments/${appointmentId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateAppointmentRequest,
      signal,
    },
    options,
  );
};

export const getUpdate1MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update1>>,
    TError,
    { officeId: string; appointmentId: string; data: UpdateAppointmentRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update1>>,
  TError,
  { officeId: string; appointmentId: string; data: UpdateAppointmentRequest },
  TContext
> => {
  const mutationKey = ['update1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update1>>,
    { officeId: string; appointmentId: string; data: UpdateAppointmentRequest }
  > = (props) => {
    const { officeId, appointmentId, data } = props ?? {};

    return update1(officeId, appointmentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type Update1MutationResult = NonNullable<Awaited<ReturnType<typeof update1>>>;
export type Update1MutationBody = UpdateAppointmentRequest;
export type Update1MutationError = unknown;

/**
 * @summary Update / reschedule an appointment
 */
export const useUpdate1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update1>>,
      TError,
      { officeId: string; appointmentId: string; data: UpdateAppointmentRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof update1>>,
  TError,
  { officeId: string; appointmentId: string; data: UpdateAppointmentRequest },
  TContext
> => {
  return useMutation(getUpdate1MutationOptions(options), queryClient);
};
/**
 * @summary Transition an appointment to a new status
 */
export const transition = (
  officeId: string,
  appointmentId: string,
  changeAppointmentStatusRequest: ChangeAppointmentStatusRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<AppointmentResponse>(
    {
      url: `/api/v1/offices/${officeId}/appointments/${appointmentId}/status`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: changeAppointmentStatusRequest,
      signal,
    },
    options,
  );
};

export const getTransitionMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof transition>>,
    TError,
    { officeId: string; appointmentId: string; data: ChangeAppointmentStatusRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof transition>>,
  TError,
  { officeId: string; appointmentId: string; data: ChangeAppointmentStatusRequest },
  TContext
> => {
  const mutationKey = ['transition'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof transition>>,
    { officeId: string; appointmentId: string; data: ChangeAppointmentStatusRequest }
  > = (props) => {
    const { officeId, appointmentId, data } = props ?? {};

    return transition(officeId, appointmentId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TransitionMutationResult = NonNullable<Awaited<ReturnType<typeof transition>>>;
export type TransitionMutationBody = ChangeAppointmentStatusRequest;
export type TransitionMutationError = unknown;

/**
 * @summary Transition an appointment to a new status
 */
export const useTransition = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof transition>>,
      TError,
      { officeId: string; appointmentId: string; data: ChangeAppointmentStatusRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof transition>>,
  TError,
  { officeId: string; appointmentId: string; data: ChangeAppointmentStatusRequest },
  TContext
> => {
  return useMutation(getTransitionMutationOptions(options), queryClient);
};
