/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { PrescriptionResponse } from '../../models/prescriptionResponse';
import type { RequestPrescriptionRequest } from '../../models/requestPrescriptionRequest';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List prescriptions of the office
 */
export const list = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<PrescriptionResponse[]>(
    { url: `/api/v1/offices/${officeId}/prescriptions`, method: 'GET', signal },
    options,
  );
};

export const getListQueryKey = (officeId: string) => {
  return ['api', 'v1', 'offices', officeId, 'prescriptions'] as const;
};

export const getListQueryOptions = <TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListQueryKey(officeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof list>>> = ({ signal }) =>
    list(officeId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type ListQueryResult = NonNullable<Awaited<ReturnType<typeof list>>>;
export type ListQueryError = unknown;

export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  officeId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof list>>, TError, Awaited<ReturnType<typeof list>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof list>>, TError, Awaited<ReturnType<typeof list>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List prescriptions of the office
 */

export function useList<TData = Awaited<ReturnType<typeof list>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListQueryOptions(officeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Create a prescription request
 */
export const request = (
  officeId: string,
  requestPrescriptionRequest: RequestPrescriptionRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PrescriptionResponse>(
    {
      url: `/api/v1/offices/${officeId}/prescriptions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: requestPrescriptionRequest,
      signal,
    },
    options,
  );
};

export const getRequestMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof request>>,
    TError,
    { officeId: string; data: RequestPrescriptionRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof request>>,
  TError,
  { officeId: string; data: RequestPrescriptionRequest },
  TContext
> => {
  const mutationKey = ['request'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof request>>,
    { officeId: string; data: RequestPrescriptionRequest }
  > = (props) => {
    const { officeId, data } = props ?? {};

    return request(officeId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RequestMutationResult = NonNullable<Awaited<ReturnType<typeof request>>>;
export type RequestMutationBody = RequestPrescriptionRequest;
export type RequestMutationError = unknown;

/**
 * @summary Create a prescription request
 */
export const useRequest = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof request>>,
      TError,
      { officeId: string; data: RequestPrescriptionRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof request>>,
  TError,
  { officeId: string; data: RequestPrescriptionRequest },
  TContext
> => {
  return useMutation(getRequestMutationOptions(options), queryClient);
};
/**
 * @summary Print / send a prescription
 */
export const print = (
  officeId: string,
  prescriptionId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PrescriptionResponse>(
    { url: `/api/v1/offices/${officeId}/prescriptions/${prescriptionId}/print`, method: 'PATCH', signal },
    options,
  );
};

export const getPrintMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof print>>,
    TError,
    { officeId: string; prescriptionId: string },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof print>>,
  TError,
  { officeId: string; prescriptionId: string },
  TContext
> => {
  const mutationKey = ['print'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof print>>,
    { officeId: string; prescriptionId: string }
  > = (props) => {
    const { officeId, prescriptionId } = props ?? {};

    return print(officeId, prescriptionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PrintMutationResult = NonNullable<Awaited<ReturnType<typeof print>>>;

export type PrintMutationError = unknown;

/**
 * @summary Print / send a prescription
 */
export const usePrint = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof print>>,
      TError,
      { officeId: string; prescriptionId: string },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof print>>,
  TError,
  { officeId: string; prescriptionId: string },
  TContext
> => {
  return useMutation(getPrintMutationOptions(options), queryClient);
};
/**
 * @summary Issue (sign) a prescription request
 */
export const issue = (
  officeId: string,
  prescriptionId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PrescriptionResponse>(
    { url: `/api/v1/offices/${officeId}/prescriptions/${prescriptionId}/issue`, method: 'PATCH', signal },
    options,
  );
};

export const getIssueMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof issue>>,
    TError,
    { officeId: string; prescriptionId: string },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof issue>>,
  TError,
  { officeId: string; prescriptionId: string },
  TContext
> => {
  const mutationKey = ['issue'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof issue>>,
    { officeId: string; prescriptionId: string }
  > = (props) => {
    const { officeId, prescriptionId } = props ?? {};

    return issue(officeId, prescriptionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type IssueMutationResult = NonNullable<Awaited<ReturnType<typeof issue>>>;

export type IssueMutationError = unknown;

/**
 * @summary Issue (sign) a prescription request
 */
export const useIssue = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof issue>>,
      TError,
      { officeId: string; prescriptionId: string },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof issue>>,
  TError,
  { officeId: string; prescriptionId: string },
  TContext
> => {
  return useMutation(getIssueMutationOptions(options), queryClient);
};
