/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { PrescriptionResponse } from '../../models/prescriptionResponse';
import type { RequestPrescriptionRequest } from '../../models/requestPrescriptionRequest';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List prescriptions of the office
 */
export const list = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<PrescriptionResponse[]>(
    { url: `/api/v1/offices/${officeId}/prescriptions`, method: 'GET', signal },
    options,
  );
};

export const getListMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof list>>, TError, { officeId: string }, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof list>>, TError, { officeId: string }, TContext> => {
  const mutationKey = ['list'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof list>>, { officeId: string }> = (props) => {
    const { officeId } = props ?? {};

    return list(officeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ListMutationResult = NonNullable<Awaited<ReturnType<typeof list>>>;

export type ListMutationError = unknown;

/**
 * @summary List prescriptions of the office
 */
export const useList = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof list>>, TError, { officeId: string }, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof list>>, TError, { officeId: string }, TContext> => {
  return useMutation(getListMutationOptions(options), queryClient);
};
/**
 * @summary Create a prescription request
 */
export const request = (
  officeId: string,
  requestPrescriptionRequest: RequestPrescriptionRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PrescriptionResponse>(
    {
      url: `/api/v1/offices/${officeId}/prescriptions`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: requestPrescriptionRequest,
      signal,
    },
    options,
  );
};

export const getRequestQueryKey = (officeId: string, requestPrescriptionRequest?: RequestPrescriptionRequest) => {
  return ['POST', 'api', 'v1', 'offices', officeId, 'prescriptions', requestPrescriptionRequest] as const;
};

export const getRequestQueryOptions = <TData = Awaited<ReturnType<typeof request>>, TError = unknown>(
  officeId: string,
  requestPrescriptionRequest: RequestPrescriptionRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof request>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRequestQueryKey(officeId, requestPrescriptionRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof request>>> = ({ signal }) =>
    request(officeId, requestPrescriptionRequest, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof request>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type RequestQueryResult = NonNullable<Awaited<ReturnType<typeof request>>>;
export type RequestQueryError = unknown;

export function useRequest<TData = Awaited<ReturnType<typeof request>>, TError = unknown>(
  officeId: string,
  requestPrescriptionRequest: RequestPrescriptionRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof request>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof request>>, TError, Awaited<ReturnType<typeof request>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRequest<TData = Awaited<ReturnType<typeof request>>, TError = unknown>(
  officeId: string,
  requestPrescriptionRequest: RequestPrescriptionRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof request>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof request>>, TError, Awaited<ReturnType<typeof request>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRequest<TData = Awaited<ReturnType<typeof request>>, TError = unknown>(
  officeId: string,
  requestPrescriptionRequest: RequestPrescriptionRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof request>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Create a prescription request
 */

export function useRequest<TData = Awaited<ReturnType<typeof request>>, TError = unknown>(
  officeId: string,
  requestPrescriptionRequest: RequestPrescriptionRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof request>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRequestQueryOptions(officeId, requestPrescriptionRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Print / send a prescription
 */
export const print = (
  officeId: string,
  prescriptionId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PrescriptionResponse>(
    { url: `/api/v1/offices/${officeId}/prescriptions/${prescriptionId}/print`, method: 'PATCH', signal },
    options,
  );
};

export const getPrintQueryKey = (officeId: string, prescriptionId: string) => {
  return ['PATCH', 'api', 'v1', 'offices', officeId, 'prescriptions', prescriptionId, 'print'] as const;
};

export const getPrintQueryOptions = <TData = Awaited<ReturnType<typeof print>>, TError = unknown>(
  officeId: string,
  prescriptionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof print>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPrintQueryKey(officeId, prescriptionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof print>>> = ({ signal }) =>
    print(officeId, prescriptionId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && prescriptionId !== null && prescriptionId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof print>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type PrintQueryResult = NonNullable<Awaited<ReturnType<typeof print>>>;
export type PrintQueryError = unknown;

export function usePrint<TData = Awaited<ReturnType<typeof print>>, TError = unknown>(
  officeId: string,
  prescriptionId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof print>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof print>>, TError, Awaited<ReturnType<typeof print>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrint<TData = Awaited<ReturnType<typeof print>>, TError = unknown>(
  officeId: string,
  prescriptionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof print>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof print>>, TError, Awaited<ReturnType<typeof print>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePrint<TData = Awaited<ReturnType<typeof print>>, TError = unknown>(
  officeId: string,
  prescriptionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof print>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Print / send a prescription
 */

export function usePrint<TData = Awaited<ReturnType<typeof print>>, TError = unknown>(
  officeId: string,
  prescriptionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof print>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPrintQueryOptions(officeId, prescriptionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Issue (sign) a prescription request
 */
export const issue = (
  officeId: string,
  prescriptionId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PrescriptionResponse>(
    { url: `/api/v1/offices/${officeId}/prescriptions/${prescriptionId}/issue`, method: 'PATCH', signal },
    options,
  );
};

export const getIssueQueryKey = (officeId: string, prescriptionId: string) => {
  return ['PATCH', 'api', 'v1', 'offices', officeId, 'prescriptions', prescriptionId, 'issue'] as const;
};

export const getIssueQueryOptions = <TData = Awaited<ReturnType<typeof issue>>, TError = unknown>(
  officeId: string,
  prescriptionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof issue>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getIssueQueryKey(officeId, prescriptionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof issue>>> = ({ signal }) =>
    issue(officeId, prescriptionId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && prescriptionId !== null && prescriptionId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof issue>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type IssueQueryResult = NonNullable<Awaited<ReturnType<typeof issue>>>;
export type IssueQueryError = unknown;

export function useIssue<TData = Awaited<ReturnType<typeof issue>>, TError = unknown>(
  officeId: string,
  prescriptionId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof issue>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof issue>>, TError, Awaited<ReturnType<typeof issue>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIssue<TData = Awaited<ReturnType<typeof issue>>, TError = unknown>(
  officeId: string,
  prescriptionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof issue>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof issue>>, TError, Awaited<ReturnType<typeof issue>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIssue<TData = Awaited<ReturnType<typeof issue>>, TError = unknown>(
  officeId: string,
  prescriptionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof issue>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Issue (sign) a prescription request
 */

export function useIssue<TData = Awaited<ReturnType<typeof issue>>, TError = unknown>(
  officeId: string,
  prescriptionId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof issue>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getIssueQueryOptions(officeId, prescriptionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
