/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */

export interface ChangePasswordRequest {
  /** @minLength 1 */
  currentPassword: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  newPassword: string;
}
