/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */

export interface InvitationResponse {
  id?: string;
  email?: string;
  roleId?: string;
  roleCode?: string;
  roleName?: string;
  status?: string;
  expiresAt?: string;
  createdAt?: string;
}
