/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */

export interface MeResponse {
  id?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  status?: string;
  officeId?: string;
  roles?: string[];
  permissions?: string[];
}
