/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */

export interface RequestPrescriptionRequest {
  /**
   * @minLength 0
   * @maxLength 300
   */
  medication: string;
  /**
   * @minLength 0
   * @maxLength 10000
   */
  instructions?: string;
  patientId: string;
}
