/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */

export interface UpdateOfficeRequest {
  /**
   * @minLength 0
   * @maxLength 150
   */
  name?: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  legalName?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  taxIdentifier?: string;
  /**
   * @minLength 0
   * @maxLength 320
   */
  email?: string;
  /**
   * @minLength 0
   * @maxLength 30
   */
  phone?: string;
  /**
   * @minLength 0
   * @maxLength 300
   */
  address?: string;
}
