/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */

export interface UpdateAppointmentRequest {
  /**
   * @minLength 0
   * @maxLength 200
   */
  title?: string;
  patientId?: string;
  startsAt?: string;
  endsAt?: string;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  notes?: string;
}
