/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AssignRoleRequest } from '../../models/assignRoleRequest';
import type { InvitationResponse } from '../../models/invitationResponse';
import type { InviteMemberRequest } from '../../models/inviteMemberRequest';
import type { OfficeMemberResponse } from '../../models/officeMemberResponse';
import type { OfficeResponse } from '../../models/officeResponse';
import type { UpdateOfficeRequest } from '../../models/updateOfficeRequest';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List office invitations
 */
export const listInvitations = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<InvitationResponse[]>(
    { url: `/api/v1/offices/${officeId}/invitations`, method: 'GET', signal },
    options,
  );
};

export const getListInvitationsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof listInvitations>>, TError, { officeId: string }, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof listInvitations>>, TError, { officeId: string }, TContext> => {
  const mutationKey = ['listInvitations'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof listInvitations>>, { officeId: string }> = (props) => {
    const { officeId } = props ?? {};

    return listInvitations(officeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ListInvitationsMutationResult = NonNullable<Awaited<ReturnType<typeof listInvitations>>>;

export type ListInvitationsMutationError = unknown;

/**
 * @summary List office invitations
 */
export const useListInvitations = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof listInvitations>>, TError, { officeId: string }, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof listInvitations>>, TError, { officeId: string }, TContext> => {
  return useMutation(getListInvitationsMutationOptions(options), queryClient);
};
/**
 * @summary Invite a collaborator to the office
 */
export const inviteMember = (
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<InvitationResponse>(
    {
      url: `/api/v1/offices/${officeId}/invitations`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: inviteMemberRequest,
      signal,
    },
    options,
  );
};

export const getInviteMemberQueryKey = (officeId: string, inviteMemberRequest?: InviteMemberRequest) => {
  return ['POST', 'api', 'v1', 'offices', officeId, 'invitations', inviteMemberRequest] as const;
};

export const getInviteMemberQueryOptions = <TData = Awaited<ReturnType<typeof inviteMember>>, TError = unknown>(
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof inviteMember>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInviteMemberQueryKey(officeId, inviteMemberRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof inviteMember>>> = ({ signal }) =>
    inviteMember(officeId, inviteMemberRequest, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof inviteMember>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type InviteMemberQueryResult = NonNullable<Awaited<ReturnType<typeof inviteMember>>>;
export type InviteMemberQueryError = unknown;

export function useInviteMember<TData = Awaited<ReturnType<typeof inviteMember>>, TError = unknown>(
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof inviteMember>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inviteMember>>,
          TError,
          Awaited<ReturnType<typeof inviteMember>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInviteMember<TData = Awaited<ReturnType<typeof inviteMember>>, TError = unknown>(
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof inviteMember>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inviteMember>>,
          TError,
          Awaited<ReturnType<typeof inviteMember>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInviteMember<TData = Awaited<ReturnType<typeof inviteMember>>, TError = unknown>(
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof inviteMember>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Invite a collaborator to the office
 */

export function useInviteMember<TData = Awaited<ReturnType<typeof inviteMember>>, TError = unknown>(
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof inviteMember>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInviteMemberQueryOptions(officeId, inviteMemberRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary View office information
 */
export const getOffice = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<OfficeResponse>({ url: `/api/v1/offices/${officeId}`, method: 'GET', signal }, options);
};

export const getGetOfficeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof getOffice>>, TError, { officeId: string }, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof getOffice>>, TError, { officeId: string }, TContext> => {
  const mutationKey = ['getOffice'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof getOffice>>, { officeId: string }> = (props) => {
    const { officeId } = props ?? {};

    return getOffice(officeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetOfficeMutationResult = NonNullable<Awaited<ReturnType<typeof getOffice>>>;

export type GetOfficeMutationError = unknown;

/**
 * @summary View office information
 */
export const useGetOffice = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof getOffice>>, TError, { officeId: string }, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof getOffice>>, TError, { officeId: string }, TContext> => {
  return useMutation(getGetOfficeMutationOptions(options), queryClient);
};
/**
 * @summary Update office information
 */
export const updateOffice = (
  officeId: string,
  updateOfficeRequest: UpdateOfficeRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<OfficeResponse>(
    {
      url: `/api/v1/offices/${officeId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateOfficeRequest,
      signal,
    },
    options,
  );
};

export const getUpdateOfficeQueryKey = (officeId: string, updateOfficeRequest?: UpdateOfficeRequest) => {
  return ['PATCH', 'api', 'v1', 'offices', officeId, updateOfficeRequest] as const;
};

export const getUpdateOfficeQueryOptions = <TData = Awaited<ReturnType<typeof updateOffice>>, TError = unknown>(
  officeId: string,
  updateOfficeRequest: UpdateOfficeRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateOffice>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUpdateOfficeQueryKey(officeId, updateOfficeRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof updateOffice>>> = ({ signal }) =>
    updateOffice(officeId, updateOfficeRequest, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof updateOffice>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type UpdateOfficeQueryResult = NonNullable<Awaited<ReturnType<typeof updateOffice>>>;
export type UpdateOfficeQueryError = unknown;

export function useUpdateOffice<TData = Awaited<ReturnType<typeof updateOffice>>, TError = unknown>(
  officeId: string,
  updateOfficeRequest: UpdateOfficeRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateOffice>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateOffice>>,
          TError,
          Awaited<ReturnType<typeof updateOffice>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateOffice<TData = Awaited<ReturnType<typeof updateOffice>>, TError = unknown>(
  officeId: string,
  updateOfficeRequest: UpdateOfficeRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateOffice>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateOffice>>,
          TError,
          Awaited<ReturnType<typeof updateOffice>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateOffice<TData = Awaited<ReturnType<typeof updateOffice>>, TError = unknown>(
  officeId: string,
  updateOfficeRequest: UpdateOfficeRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateOffice>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update office information
 */

export function useUpdateOffice<TData = Awaited<ReturnType<typeof updateOffice>>, TError = unknown>(
  officeId: string,
  updateOfficeRequest: UpdateOfficeRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateOffice>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUpdateOfficeQueryOptions(officeId, updateOfficeRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Assign an office role to a member
 */
export const assignRole = (
  officeId: string,
  userId: string,
  assignRoleRequest: AssignRoleRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    {
      url: `/api/v1/offices/${officeId}/members/${userId}/role`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: assignRoleRequest,
      signal,
    },
    options,
  );
};

export const getAssignRoleQueryKey = (officeId: string, userId: string, assignRoleRequest?: AssignRoleRequest) => {
  return ['PATCH', 'api', 'v1', 'offices', officeId, 'members', userId, 'role', assignRoleRequest] as const;
};

export const getAssignRoleQueryOptions = <TData = Awaited<ReturnType<typeof assignRole>>, TError = unknown>(
  officeId: string,
  userId: string,
  assignRoleRequest: AssignRoleRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assignRole>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAssignRoleQueryKey(officeId, userId, assignRoleRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof assignRole>>> = ({ signal }) =>
    assignRole(officeId, userId, assignRoleRequest, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof assignRole>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type AssignRoleQueryResult = NonNullable<Awaited<ReturnType<typeof assignRole>>>;
export type AssignRoleQueryError = unknown;

export function useAssignRole<TData = Awaited<ReturnType<typeof assignRole>>, TError = unknown>(
  officeId: string,
  userId: string,
  assignRoleRequest: AssignRoleRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof assignRole>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assignRole>>,
          TError,
          Awaited<ReturnType<typeof assignRole>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAssignRole<TData = Awaited<ReturnType<typeof assignRole>>, TError = unknown>(
  officeId: string,
  userId: string,
  assignRoleRequest: AssignRoleRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assignRole>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assignRole>>,
          TError,
          Awaited<ReturnType<typeof assignRole>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAssignRole<TData = Awaited<ReturnType<typeof assignRole>>, TError = unknown>(
  officeId: string,
  userId: string,
  assignRoleRequest: AssignRoleRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assignRole>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Assign an office role to a member
 */

export function useAssignRole<TData = Awaited<ReturnType<typeof assignRole>>, TError = unknown>(
  officeId: string,
  userId: string,
  assignRoleRequest: AssignRoleRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof assignRole>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAssignRoleQueryOptions(officeId, userId, assignRoleRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List office members
 */
export const listMembers1 = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<OfficeMemberResponse[]>(
    { url: `/api/v1/offices/${officeId}/members`, method: 'GET', signal },
    options,
  );
};

export const getListMembers1MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof listMembers1>>, TError, { officeId: string }, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof listMembers1>>, TError, { officeId: string }, TContext> => {
  const mutationKey = ['listMembers1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof listMembers1>>, { officeId: string }> = (props) => {
    const { officeId } = props ?? {};

    return listMembers1(officeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ListMembers1MutationResult = NonNullable<Awaited<ReturnType<typeof listMembers1>>>;

export type ListMembers1MutationError = unknown;

/**
 * @summary List office members
 */
export const useListMembers1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof listMembers1>>, TError, { officeId: string }, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof listMembers1>>, TError, { officeId: string }, TContext> => {
  return useMutation(getListMembers1MutationOptions(options), queryClient);
};
/**
 * @summary Remove a member from the office
 */
export const removeMember = (
  officeId: string,
  userId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>({ url: `/api/v1/offices/${officeId}/members/${userId}`, method: 'DELETE', signal }, options);
};

export const getRemoveMemberQueryKey = (officeId: string, userId: string) => {
  return ['DELETE', 'api', 'v1', 'offices', officeId, 'members', userId] as const;
};

export const getRemoveMemberQueryOptions = <TData = Awaited<ReturnType<typeof removeMember>>, TError = unknown>(
  officeId: string,
  userId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeMember>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRemoveMemberQueryKey(officeId, userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof removeMember>>> = ({ signal }) =>
    removeMember(officeId, userId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && userId !== null && userId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof removeMember>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type RemoveMemberQueryResult = NonNullable<Awaited<ReturnType<typeof removeMember>>>;
export type RemoveMemberQueryError = unknown;

export function useRemoveMember<TData = Awaited<ReturnType<typeof removeMember>>, TError = unknown>(
  officeId: string,
  userId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeMember>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof removeMember>>,
          TError,
          Awaited<ReturnType<typeof removeMember>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRemoveMember<TData = Awaited<ReturnType<typeof removeMember>>, TError = unknown>(
  officeId: string,
  userId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeMember>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof removeMember>>,
          TError,
          Awaited<ReturnType<typeof removeMember>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRemoveMember<TData = Awaited<ReturnType<typeof removeMember>>, TError = unknown>(
  officeId: string,
  userId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeMember>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Remove a member from the office
 */

export function useRemoveMember<TData = Awaited<ReturnType<typeof removeMember>>, TError = unknown>(
  officeId: string,
  userId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof removeMember>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRemoveMemberQueryOptions(officeId, userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Revoke an office role from a member
 */
export const revokeRole = (
  officeId: string,
  userId: string,
  roleId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    { url: `/api/v1/offices/${officeId}/members/${userId}/roles/${roleId}`, method: 'DELETE', signal },
    options,
  );
};

export const getRevokeRoleQueryKey = (officeId: string, userId: string, roleId: string) => {
  return ['DELETE', 'api', 'v1', 'offices', officeId, 'members', userId, 'roles', roleId] as const;
};

export const getRevokeRoleQueryOptions = <TData = Awaited<ReturnType<typeof revokeRole>>, TError = unknown>(
  officeId: string,
  userId: string,
  roleId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof revokeRole>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRevokeRoleQueryKey(officeId, userId, roleId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof revokeRole>>> = ({ signal }) =>
    revokeRole(officeId, userId, roleId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled:
      officeId !== null &&
      officeId !== undefined &&
      userId !== null &&
      userId !== undefined &&
      roleId !== null &&
      roleId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof revokeRole>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type RevokeRoleQueryResult = NonNullable<Awaited<ReturnType<typeof revokeRole>>>;
export type RevokeRoleQueryError = unknown;

export function useRevokeRole<TData = Awaited<ReturnType<typeof revokeRole>>, TError = unknown>(
  officeId: string,
  userId: string,
  roleId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof revokeRole>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof revokeRole>>,
          TError,
          Awaited<ReturnType<typeof revokeRole>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRevokeRole<TData = Awaited<ReturnType<typeof revokeRole>>, TError = unknown>(
  officeId: string,
  userId: string,
  roleId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof revokeRole>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof revokeRole>>,
          TError,
          Awaited<ReturnType<typeof revokeRole>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRevokeRole<TData = Awaited<ReturnType<typeof revokeRole>>, TError = unknown>(
  officeId: string,
  userId: string,
  roleId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof revokeRole>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Revoke an office role from a member
 */

export function useRevokeRole<TData = Awaited<ReturnType<typeof revokeRole>>, TError = unknown>(
  officeId: string,
  userId: string,
  roleId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof revokeRole>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRevokeRoleQueryOptions(officeId, userId, roleId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Revoke a pending invitation
 */
export const revokeInvitation = (
  officeId: string,
  invitationId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    { url: `/api/v1/offices/${officeId}/invitations/${invitationId}`, method: 'DELETE', signal },
    options,
  );
};

export const getRevokeInvitationQueryKey = (officeId: string, invitationId: string) => {
  return ['DELETE', 'api', 'v1', 'offices', officeId, 'invitations', invitationId] as const;
};

export const getRevokeInvitationQueryOptions = <TData = Awaited<ReturnType<typeof revokeInvitation>>, TError = unknown>(
  officeId: string,
  invitationId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof revokeInvitation>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRevokeInvitationQueryKey(officeId, invitationId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof revokeInvitation>>> = ({ signal }) =>
    revokeInvitation(officeId, invitationId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && invitationId !== null && invitationId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof revokeInvitation>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type RevokeInvitationQueryResult = NonNullable<Awaited<ReturnType<typeof revokeInvitation>>>;
export type RevokeInvitationQueryError = unknown;

export function useRevokeInvitation<TData = Awaited<ReturnType<typeof revokeInvitation>>, TError = unknown>(
  officeId: string,
  invitationId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof revokeInvitation>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof revokeInvitation>>,
          TError,
          Awaited<ReturnType<typeof revokeInvitation>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRevokeInvitation<TData = Awaited<ReturnType<typeof revokeInvitation>>, TError = unknown>(
  officeId: string,
  invitationId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof revokeInvitation>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof revokeInvitation>>,
          TError,
          Awaited<ReturnType<typeof revokeInvitation>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRevokeInvitation<TData = Awaited<ReturnType<typeof revokeInvitation>>, TError = unknown>(
  officeId: string,
  invitationId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof revokeInvitation>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Revoke a pending invitation
 */

export function useRevokeInvitation<TData = Awaited<ReturnType<typeof revokeInvitation>>, TError = unknown>(
  officeId: string,
  invitationId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof revokeInvitation>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRevokeInvitationQueryOptions(officeId, invitationId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
