/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AssignRoleRequest } from '../../models/assignRoleRequest';
import type { InvitationResponse } from '../../models/invitationResponse';
import type { InviteMemberRequest } from '../../models/inviteMemberRequest';
import type { OfficeMemberResponse } from '../../models/officeMemberResponse';
import type { OfficeResponse } from '../../models/officeResponse';
import type { UpdateOfficeRequest } from '../../models/updateOfficeRequest';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List office invitations
 */
export const listInvitations = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<InvitationResponse[]>(
    { url: `/api/v1/offices/${officeId}/invitations`, method: 'GET', signal },
    options,
  );
};

export const getListInvitationsQueryKey = (officeId: string) => {
  return ['api', 'v1', 'offices', officeId, 'invitations'] as const;
};

export const getListInvitationsQueryOptions = <TData = Awaited<ReturnType<typeof listInvitations>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listInvitations>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListInvitationsQueryKey(officeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listInvitations>>> = ({ signal }) =>
    listInvitations(officeId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof listInvitations>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type ListInvitationsQueryResult = NonNullable<Awaited<ReturnType<typeof listInvitations>>>;
export type ListInvitationsQueryError = unknown;

export function useListInvitations<TData = Awaited<ReturnType<typeof listInvitations>>, TError = unknown>(
  officeId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listInvitations>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInvitations>>,
          TError,
          Awaited<ReturnType<typeof listInvitations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListInvitations<TData = Awaited<ReturnType<typeof listInvitations>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listInvitations>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listInvitations>>,
          TError,
          Awaited<ReturnType<typeof listInvitations>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListInvitations<TData = Awaited<ReturnType<typeof listInvitations>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listInvitations>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List office invitations
 */

export function useListInvitations<TData = Awaited<ReturnType<typeof listInvitations>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listInvitations>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListInvitationsQueryOptions(officeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Invite a collaborator to the office
 */
export const inviteMember = (
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<InvitationResponse>(
    {
      url: `/api/v1/offices/${officeId}/invitations`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: inviteMemberRequest,
      signal,
    },
    options,
  );
};

export const getInviteMemberMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof inviteMember>>,
    TError,
    { officeId: string; data: InviteMemberRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof inviteMember>>,
  TError,
  { officeId: string; data: InviteMemberRequest },
  TContext
> => {
  const mutationKey = ['inviteMember'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof inviteMember>>,
    { officeId: string; data: InviteMemberRequest }
  > = (props) => {
    const { officeId, data } = props ?? {};

    return inviteMember(officeId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InviteMemberMutationResult = NonNullable<Awaited<ReturnType<typeof inviteMember>>>;
export type InviteMemberMutationBody = InviteMemberRequest;
export type InviteMemberMutationError = unknown;

/**
 * @summary Invite a collaborator to the office
 */
export const useInviteMember = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof inviteMember>>,
      TError,
      { officeId: string; data: InviteMemberRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof inviteMember>>,
  TError,
  { officeId: string; data: InviteMemberRequest },
  TContext
> => {
  return useMutation(getInviteMemberMutationOptions(options), queryClient);
};
/**
 * @summary View office information
 */
export const getOffice = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<OfficeResponse>({ url: `/api/v1/offices/${officeId}`, method: 'GET', signal }, options);
};

export const getGetOfficeQueryKey = (officeId: string) => {
  return ['api', 'v1', 'offices', officeId] as const;
};

export const getGetOfficeQueryOptions = <TData = Awaited<ReturnType<typeof getOffice>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOffice>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOfficeQueryKey(officeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOffice>>> = ({ signal }) =>
    getOffice(officeId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getOffice>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetOfficeQueryResult = NonNullable<Awaited<ReturnType<typeof getOffice>>>;
export type GetOfficeQueryError = unknown;

export function useGetOffice<TData = Awaited<ReturnType<typeof getOffice>>, TError = unknown>(
  officeId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOffice>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof getOffice>>, TError, Awaited<ReturnType<typeof getOffice>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOffice<TData = Awaited<ReturnType<typeof getOffice>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOffice>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOffice>>,
          TError,
          Awaited<ReturnType<typeof getOffice>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOffice<TData = Awaited<ReturnType<typeof getOffice>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOffice>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary View office information
 */

export function useGetOffice<TData = Awaited<ReturnType<typeof getOffice>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOffice>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetOfficeQueryOptions(officeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Update office information
 */
export const updateOffice = (
  officeId: string,
  updateOfficeRequest: UpdateOfficeRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<OfficeResponse>(
    {
      url: `/api/v1/offices/${officeId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateOfficeRequest,
      signal,
    },
    options,
  );
};

export const getUpdateOfficeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateOffice>>,
    TError,
    { officeId: string; data: UpdateOfficeRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateOffice>>,
  TError,
  { officeId: string; data: UpdateOfficeRequest },
  TContext
> => {
  const mutationKey = ['updateOffice'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateOffice>>,
    { officeId: string; data: UpdateOfficeRequest }
  > = (props) => {
    const { officeId, data } = props ?? {};

    return updateOffice(officeId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateOfficeMutationResult = NonNullable<Awaited<ReturnType<typeof updateOffice>>>;
export type UpdateOfficeMutationBody = UpdateOfficeRequest;
export type UpdateOfficeMutationError = unknown;

/**
 * @summary Update office information
 */
export const useUpdateOffice = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateOffice>>,
      TError,
      { officeId: string; data: UpdateOfficeRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateOffice>>,
  TError,
  { officeId: string; data: UpdateOfficeRequest },
  TContext
> => {
  return useMutation(getUpdateOfficeMutationOptions(options), queryClient);
};
/**
 * @summary Assign an office role to a member
 */
export const assignRole = (
  officeId: string,
  userId: string,
  assignRoleRequest: AssignRoleRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    {
      url: `/api/v1/offices/${officeId}/members/${userId}/role`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: assignRoleRequest,
      signal,
    },
    options,
  );
};

export const getAssignRoleMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assignRole>>,
    TError,
    { officeId: string; userId: string; data: AssignRoleRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assignRole>>,
  TError,
  { officeId: string; userId: string; data: AssignRoleRequest },
  TContext
> => {
  const mutationKey = ['assignRole'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assignRole>>,
    { officeId: string; userId: string; data: AssignRoleRequest }
  > = (props) => {
    const { officeId, userId, data } = props ?? {};

    return assignRole(officeId, userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssignRoleMutationResult = NonNullable<Awaited<ReturnType<typeof assignRole>>>;
export type AssignRoleMutationBody = AssignRoleRequest;
export type AssignRoleMutationError = unknown;

/**
 * @summary Assign an office role to a member
 */
export const useAssignRole = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof assignRole>>,
      TError,
      { officeId: string; userId: string; data: AssignRoleRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof assignRole>>,
  TError,
  { officeId: string; userId: string; data: AssignRoleRequest },
  TContext
> => {
  return useMutation(getAssignRoleMutationOptions(options), queryClient);
};
/**
 * @summary List office members
 */
export const listMembers1 = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<OfficeMemberResponse[]>(
    { url: `/api/v1/offices/${officeId}/members`, method: 'GET', signal },
    options,
  );
};

export const getListMembers1QueryKey = (officeId: string) => {
  return ['api', 'v1', 'offices', officeId, 'members'] as const;
};

export const getListMembers1QueryOptions = <TData = Awaited<ReturnType<typeof listMembers1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMembers1QueryKey(officeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMembers1>>> = ({ signal }) =>
    listMembers1(officeId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof listMembers1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type ListMembers1QueryResult = NonNullable<Awaited<ReturnType<typeof listMembers1>>>;
export type ListMembers1QueryError = unknown;

export function useListMembers1<TData = Awaited<ReturnType<typeof listMembers1>>, TError = unknown>(
  officeId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers1>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembers1>>,
          TError,
          Awaited<ReturnType<typeof listMembers1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListMembers1<TData = Awaited<ReturnType<typeof listMembers1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers1>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembers1>>,
          TError,
          Awaited<ReturnType<typeof listMembers1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListMembers1<TData = Awaited<ReturnType<typeof listMembers1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List office members
 */

export function useListMembers1<TData = Awaited<ReturnType<typeof listMembers1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListMembers1QueryOptions(officeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Remove a member from the office
 */
export const removeMember = (
  officeId: string,
  userId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>({ url: `/api/v1/offices/${officeId}/members/${userId}`, method: 'DELETE', signal }, options);
};

export const getRemoveMemberMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeMember>>,
    TError,
    { officeId: string; userId: string },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeMember>>,
  TError,
  { officeId: string; userId: string },
  TContext
> => {
  const mutationKey = ['removeMember'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeMember>>, { officeId: string; userId: string }> = (
    props,
  ) => {
    const { officeId, userId } = props ?? {};

    return removeMember(officeId, userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveMemberMutationResult = NonNullable<Awaited<ReturnType<typeof removeMember>>>;

export type RemoveMemberMutationError = unknown;

/**
 * @summary Remove a member from the office
 */
export const useRemoveMember = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeMember>>,
      TError,
      { officeId: string; userId: string },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removeMember>>,
  TError,
  { officeId: string; userId: string },
  TContext
> => {
  return useMutation(getRemoveMemberMutationOptions(options), queryClient);
};
/**
 * @summary Revoke an office role from a member
 */
export const revokeRole = (
  officeId: string,
  userId: string,
  roleId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    { url: `/api/v1/offices/${officeId}/members/${userId}/roles/${roleId}`, method: 'DELETE', signal },
    options,
  );
};

export const getRevokeRoleMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof revokeRole>>,
    TError,
    { officeId: string; userId: string; roleId: string },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof revokeRole>>,
  TError,
  { officeId: string; userId: string; roleId: string },
  TContext
> => {
  const mutationKey = ['revokeRole'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof revokeRole>>,
    { officeId: string; userId: string; roleId: string }
  > = (props) => {
    const { officeId, userId, roleId } = props ?? {};

    return revokeRole(officeId, userId, roleId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RevokeRoleMutationResult = NonNullable<Awaited<ReturnType<typeof revokeRole>>>;

export type RevokeRoleMutationError = unknown;

/**
 * @summary Revoke an office role from a member
 */
export const useRevokeRole = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof revokeRole>>,
      TError,
      { officeId: string; userId: string; roleId: string },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof revokeRole>>,
  TError,
  { officeId: string; userId: string; roleId: string },
  TContext
> => {
  return useMutation(getRevokeRoleMutationOptions(options), queryClient);
};
/**
 * @summary Revoke a pending invitation
 */
export const revokeInvitation = (
  officeId: string,
  invitationId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    { url: `/api/v1/offices/${officeId}/invitations/${invitationId}`, method: 'DELETE', signal },
    options,
  );
};

export const getRevokeInvitationMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof revokeInvitation>>,
    TError,
    { officeId: string; invitationId: string },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof revokeInvitation>>,
  TError,
  { officeId: string; invitationId: string },
  TContext
> => {
  const mutationKey = ['revokeInvitation'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof revokeInvitation>>,
    { officeId: string; invitationId: string }
  > = (props) => {
    const { officeId, invitationId } = props ?? {};

    return revokeInvitation(officeId, invitationId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RevokeInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof revokeInvitation>>>;

export type RevokeInvitationMutationError = unknown;

/**
 * @summary Revoke a pending invitation
 */
export const useRevokeInvitation = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof revokeInvitation>>,
      TError,
      { officeId: string; invitationId: string },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof revokeInvitation>>,
  TError,
  { officeId: string; invitationId: string },
  TContext
> => {
  return useMutation(getRevokeInvitationMutationOptions(options), queryClient);
};
