/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateOfficeRequest } from '../../models/createOfficeRequest';
import type { InvitationResponse } from '../../models/invitationResponse';
import type { InviteMemberRequest } from '../../models/inviteMemberRequest';
import type { OfficeMemberResponse } from '../../models/officeMemberResponse';
import type { OfficeResponse } from '../../models/officeResponse';
import type { PermissionResponse } from '../../models/permissionResponse';
import type { RoleResponse } from '../../models/roleResponse';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List all offices
 */
export const listOffices = (options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<OfficeResponse[]>({ url: `/api/v1/admin/offices`, method: 'GET', signal }, options);
};

export const getListOfficesMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof listOffices>>, TError, void, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof listOffices>>, TError, void, TContext> => {
  const mutationKey = ['listOffices'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof listOffices>>, void> = () => {
    return listOffices(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ListOfficesMutationResult = NonNullable<Awaited<ReturnType<typeof listOffices>>>;

export type ListOfficesMutationError = unknown;

/**
 * @summary List all offices
 */
export const useListOffices = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof listOffices>>, TError, void, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof listOffices>>, TError, void, TContext> => {
  return useMutation(getListOfficesMutationOptions(options), queryClient);
};
/**
 * @summary Provision a new office with its titular doctor
 */
export const createOffice = (
  createOfficeRequest: CreateOfficeRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<OfficeResponse>(
    {
      url: `/api/v1/admin/offices`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createOfficeRequest,
      signal,
    },
    options,
  );
};

export const getCreateOfficeQueryKey = (createOfficeRequest?: CreateOfficeRequest) => {
  return ['POST', 'api', 'v1', 'admin', 'offices', createOfficeRequest] as const;
};

export const getCreateOfficeQueryOptions = <TData = Awaited<ReturnType<typeof createOffice>>, TError = unknown>(
  createOfficeRequest: CreateOfficeRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createOffice>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCreateOfficeQueryKey(createOfficeRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof createOffice>>> = ({ signal }) =>
    createOffice(createOfficeRequest, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof createOffice>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CreateOfficeQueryResult = NonNullable<Awaited<ReturnType<typeof createOffice>>>;
export type CreateOfficeQueryError = unknown;

export function useCreateOffice<TData = Awaited<ReturnType<typeof createOffice>>, TError = unknown>(
  createOfficeRequest: CreateOfficeRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof createOffice>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createOffice>>,
          TError,
          Awaited<ReturnType<typeof createOffice>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateOffice<TData = Awaited<ReturnType<typeof createOffice>>, TError = unknown>(
  createOfficeRequest: CreateOfficeRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createOffice>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createOffice>>,
          TError,
          Awaited<ReturnType<typeof createOffice>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreateOffice<TData = Awaited<ReturnType<typeof createOffice>>, TError = unknown>(
  createOfficeRequest: CreateOfficeRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createOffice>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Provision a new office with its titular doctor
 */

export function useCreateOffice<TData = Awaited<ReturnType<typeof createOffice>>, TError = unknown>(
  createOfficeRequest: CreateOfficeRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof createOffice>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCreateOfficeQueryOptions(createOfficeRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List the active members of an office
 */
export const listMembers = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<OfficeMemberResponse[]>(
    { url: `/api/v1/admin/offices/${officeId}/members`, method: 'GET', signal },
    options,
  );
};

export const getListMembersMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof listMembers>>, TError, { officeId: string }, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof listMembers>>, TError, { officeId: string }, TContext> => {
  const mutationKey = ['listMembers'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof listMembers>>, { officeId: string }> = (props) => {
    const { officeId } = props ?? {};

    return listMembers(officeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ListMembersMutationResult = NonNullable<Awaited<ReturnType<typeof listMembers>>>;

export type ListMembersMutationError = unknown;

/**
 * @summary List the active members of an office
 */
export const useListMembers = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof listMembers>>, TError, { officeId: string }, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof listMembers>>, TError, { officeId: string }, TContext> => {
  return useMutation(getListMembersMutationOptions(options), queryClient);
};
/**
 * @summary Provision a collaborator into an office
 */
export const addMember = (
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<InvitationResponse>(
    {
      url: `/api/v1/admin/offices/${officeId}/members`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: inviteMemberRequest,
      signal,
    },
    options,
  );
};

export const getAddMemberQueryKey = (officeId: string, inviteMemberRequest?: InviteMemberRequest) => {
  return ['POST', 'api', 'v1', 'admin', 'offices', officeId, 'members', inviteMemberRequest] as const;
};

export const getAddMemberQueryOptions = <TData = Awaited<ReturnType<typeof addMember>>, TError = unknown>(
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addMember>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAddMemberQueryKey(officeId, inviteMemberRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof addMember>>> = ({ signal }) =>
    addMember(officeId, inviteMemberRequest, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof addMember>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type AddMemberQueryResult = NonNullable<Awaited<ReturnType<typeof addMember>>>;
export type AddMemberQueryError = unknown;

export function useAddMember<TData = Awaited<ReturnType<typeof addMember>>, TError = unknown>(
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof addMember>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof addMember>>, TError, Awaited<ReturnType<typeof addMember>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAddMember<TData = Awaited<ReturnType<typeof addMember>>, TError = unknown>(
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addMember>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof addMember>>,
          TError,
          Awaited<ReturnType<typeof addMember>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAddMember<TData = Awaited<ReturnType<typeof addMember>>, TError = unknown>(
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addMember>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Provision a collaborator into an office
 */

export function useAddMember<TData = Awaited<ReturnType<typeof addMember>>, TError = unknown>(
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof addMember>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAddMemberQueryOptions(officeId, inviteMemberRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List the role catalog
 */
export const listRoles = (options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<RoleResponse[]>({ url: `/api/v1/admin/roles`, method: 'GET', signal }, options);
};

export const getListRolesMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof listRoles>>, TError, void, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof listRoles>>, TError, void, TContext> => {
  const mutationKey = ['listRoles'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof listRoles>>, void> = () => {
    return listRoles(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ListRolesMutationResult = NonNullable<Awaited<ReturnType<typeof listRoles>>>;

export type ListRolesMutationError = unknown;

/**
 * @summary List the role catalog
 */
export const useListRoles = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof listRoles>>, TError, void, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof listRoles>>, TError, void, TContext> => {
  return useMutation(getListRolesMutationOptions(options), queryClient);
};
/**
 * @summary List the permission catalog
 */
export const listPermissions = (options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<PermissionResponse[]>({ url: `/api/v1/admin/permissions`, method: 'GET', signal }, options);
};

export const getListPermissionsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof listPermissions>>, TError, void, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof listPermissions>>, TError, void, TContext> => {
  const mutationKey = ['listPermissions'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof listPermissions>>, void> = () => {
    return listPermissions(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ListPermissionsMutationResult = NonNullable<Awaited<ReturnType<typeof listPermissions>>>;

export type ListPermissionsMutationError = unknown;

/**
 * @summary List the permission catalog
 */
export const useListPermissions = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof listPermissions>>, TError, void, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof listPermissions>>, TError, void, TContext> => {
  return useMutation(getListPermissionsMutationOptions(options), queryClient);
};
/**
 * @summary View an office
 */
export const getOffice1 = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<OfficeResponse>({ url: `/api/v1/admin/offices/${officeId}`, method: 'GET', signal }, options);
};

export const getGetOffice1MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof getOffice1>>, TError, { officeId: string }, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof getOffice1>>, TError, { officeId: string }, TContext> => {
  const mutationKey = ['getOffice1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof getOffice1>>, { officeId: string }> = (props) => {
    const { officeId } = props ?? {};

    return getOffice1(officeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetOffice1MutationResult = NonNullable<Awaited<ReturnType<typeof getOffice1>>>;

export type GetOffice1MutationError = unknown;

/**
 * @summary View an office
 */
export const useGetOffice1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof getOffice1>>, TError, { officeId: string }, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof getOffice1>>, TError, { officeId: string }, TContext> => {
  return useMutation(getGetOffice1MutationOptions(options), queryClient);
};
