/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateOfficeRequest } from '../../models/createOfficeRequest';
import type { InvitationResponse } from '../../models/invitationResponse';
import type { InviteMemberRequest } from '../../models/inviteMemberRequest';
import type { OfficeMemberResponse } from '../../models/officeMemberResponse';
import type { OfficeResponse } from '../../models/officeResponse';
import type { PermissionResponse } from '../../models/permissionResponse';
import type { RoleResponse } from '../../models/roleResponse';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List all offices
 */
export const listOffices = (options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<OfficeResponse[]>({ url: `/api/v1/admin/offices`, method: 'GET', signal }, options);
};

export const getListOfficesQueryKey = () => {
  return ['api', 'v1', 'admin', 'offices'] as const;
};

export const getListOfficesQueryOptions = <
  TData = Awaited<ReturnType<typeof listOffices>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listOffices>>, TError, TData>>;
  request?: SecondParameter<typeof mutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListOfficesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listOffices>>> = ({ signal }) =>
    listOffices(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listOffices>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListOfficesQueryResult = NonNullable<Awaited<ReturnType<typeof listOffices>>>;
export type ListOfficesQueryError = unknown;

export function useListOffices<TData = Awaited<ReturnType<typeof listOffices>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listOffices>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOffices>>,
          TError,
          Awaited<ReturnType<typeof listOffices>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListOffices<TData = Awaited<ReturnType<typeof listOffices>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listOffices>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listOffices>>,
          TError,
          Awaited<ReturnType<typeof listOffices>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListOffices<TData = Awaited<ReturnType<typeof listOffices>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listOffices>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List all offices
 */

export function useListOffices<TData = Awaited<ReturnType<typeof listOffices>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listOffices>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListOfficesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Provision a new office with its titular doctor
 */
export const createOffice = (
  createOfficeRequest: CreateOfficeRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<OfficeResponse>(
    {
      url: `/api/v1/admin/offices`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createOfficeRequest,
      signal,
    },
    options,
  );
};

export const getCreateOfficeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOffice>>,
    TError,
    { data: CreateOfficeRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof createOffice>>, TError, { data: CreateOfficeRequest }, TContext> => {
  const mutationKey = ['createOffice'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOffice>>, { data: CreateOfficeRequest }> = (
    props,
  ) => {
    const { data } = props ?? {};

    return createOffice(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOfficeMutationResult = NonNullable<Awaited<ReturnType<typeof createOffice>>>;
export type CreateOfficeMutationBody = CreateOfficeRequest;
export type CreateOfficeMutationError = unknown;

/**
 * @summary Provision a new office with its titular doctor
 */
export const useCreateOffice = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createOffice>>,
      TError,
      { data: CreateOfficeRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof createOffice>>, TError, { data: CreateOfficeRequest }, TContext> => {
  return useMutation(getCreateOfficeMutationOptions(options), queryClient);
};
/**
 * @summary List the active members of an office
 */
export const listMembers = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<OfficeMemberResponse[]>(
    { url: `/api/v1/admin/offices/${officeId}/members`, method: 'GET', signal },
    options,
  );
};

export const getListMembersQueryKey = (officeId: string) => {
  return ['api', 'v1', 'admin', 'offices', officeId, 'members'] as const;
};

export const getListMembersQueryOptions = <TData = Awaited<ReturnType<typeof listMembers>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMembersQueryKey(officeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMembers>>> = ({ signal }) =>
    listMembers(officeId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type ListMembersQueryResult = NonNullable<Awaited<ReturnType<typeof listMembers>>>;
export type ListMembersQueryError = unknown;

export function useListMembers<TData = Awaited<ReturnType<typeof listMembers>>, TError = unknown>(
  officeId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembers>>,
          TError,
          Awaited<ReturnType<typeof listMembers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListMembers<TData = Awaited<ReturnType<typeof listMembers>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembers>>,
          TError,
          Awaited<ReturnType<typeof listMembers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListMembers<TData = Awaited<ReturnType<typeof listMembers>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List the active members of an office
 */

export function useListMembers<TData = Awaited<ReturnType<typeof listMembers>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembers>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListMembersQueryOptions(officeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Provision a collaborator into an office
 */
export const addMember = (
  officeId: string,
  inviteMemberRequest: InviteMemberRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<InvitationResponse>(
    {
      url: `/api/v1/admin/offices/${officeId}/members`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: inviteMemberRequest,
      signal,
    },
    options,
  );
};

export const getAddMemberMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addMember>>,
    TError,
    { officeId: string; data: InviteMemberRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addMember>>,
  TError,
  { officeId: string; data: InviteMemberRequest },
  TContext
> => {
  const mutationKey = ['addMember'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addMember>>,
    { officeId: string; data: InviteMemberRequest }
  > = (props) => {
    const { officeId, data } = props ?? {};

    return addMember(officeId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddMemberMutationResult = NonNullable<Awaited<ReturnType<typeof addMember>>>;
export type AddMemberMutationBody = InviteMemberRequest;
export type AddMemberMutationError = unknown;

/**
 * @summary Provision a collaborator into an office
 */
export const useAddMember = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addMember>>,
      TError,
      { officeId: string; data: InviteMemberRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addMember>>,
  TError,
  { officeId: string; data: InviteMemberRequest },
  TContext
> => {
  return useMutation(getAddMemberMutationOptions(options), queryClient);
};
/**
 * @summary List the role catalog
 */
export const listRoles = (options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<RoleResponse[]>({ url: `/api/v1/admin/roles`, method: 'GET', signal }, options);
};

export const getListRolesQueryKey = () => {
  return ['api', 'v1', 'admin', 'roles'] as const;
};

export const getListRolesQueryOptions = <TData = Awaited<ReturnType<typeof listRoles>>, TError = unknown>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData>>;
  request?: SecondParameter<typeof mutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListRolesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRoles>>> = ({ signal }) =>
    listRoles(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listRoles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListRolesQueryResult = NonNullable<Awaited<ReturnType<typeof listRoles>>>;
export type ListRolesQueryError = unknown;

export function useListRoles<TData = Awaited<ReturnType<typeof listRoles>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof listRoles>>, TError, Awaited<ReturnType<typeof listRoles>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListRoles<TData = Awaited<ReturnType<typeof listRoles>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRoles>>,
          TError,
          Awaited<ReturnType<typeof listRoles>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListRoles<TData = Awaited<ReturnType<typeof listRoles>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List the role catalog
 */

export function useListRoles<TData = Awaited<ReturnType<typeof listRoles>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoles>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListRolesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List the permission catalog
 */
export const listPermissions = (options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<PermissionResponse[]>({ url: `/api/v1/admin/permissions`, method: 'GET', signal }, options);
};

export const getListPermissionsQueryKey = () => {
  return ['api', 'v1', 'admin', 'permissions'] as const;
};

export const getListPermissionsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPermissions>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPermissions>>, TError, TData>>;
  request?: SecondParameter<typeof mutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListPermissionsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPermissions>>> = ({ signal }) =>
    listPermissions(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPermissions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof listPermissions>>>;
export type ListPermissionsQueryError = unknown;

export function useListPermissions<TData = Awaited<ReturnType<typeof listPermissions>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPermissions>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPermissions>>,
          TError,
          Awaited<ReturnType<typeof listPermissions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListPermissions<TData = Awaited<ReturnType<typeof listPermissions>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPermissions>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPermissions>>,
          TError,
          Awaited<ReturnType<typeof listPermissions>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListPermissions<TData = Awaited<ReturnType<typeof listPermissions>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPermissions>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List the permission catalog
 */

export function useListPermissions<TData = Awaited<ReturnType<typeof listPermissions>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPermissions>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListPermissionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary View an office
 */
export const getOffice1 = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<OfficeResponse>({ url: `/api/v1/admin/offices/${officeId}`, method: 'GET', signal }, options);
};

export const getGetOffice1QueryKey = (officeId: string) => {
  return ['api', 'v1', 'admin', 'offices', officeId] as const;
};

export const getGetOffice1QueryOptions = <TData = Awaited<ReturnType<typeof getOffice1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOffice1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOffice1QueryKey(officeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOffice1>>> = ({ signal }) =>
    getOffice1(officeId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getOffice1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetOffice1QueryResult = NonNullable<Awaited<ReturnType<typeof getOffice1>>>;
export type GetOffice1QueryError = unknown;

export function useGetOffice1<TData = Awaited<ReturnType<typeof getOffice1>>, TError = unknown>(
  officeId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOffice1>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOffice1>>,
          TError,
          Awaited<ReturnType<typeof getOffice1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOffice1<TData = Awaited<ReturnType<typeof getOffice1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOffice1>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOffice1>>,
          TError,
          Awaited<ReturnType<typeof getOffice1>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOffice1<TData = Awaited<ReturnType<typeof getOffice1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOffice1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary View an office
 */

export function useGetOffice1<TData = Awaited<ReturnType<typeof getOffice1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOffice1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetOffice1QueryOptions(officeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
