CREATE ROLE app_user LOGIN PASSWORD 'app_user';

GRANT USAGE ON SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES FOR ROLE db_owner IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES FOR ROLE db_owner IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO app_user;
