/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { ClinicalNotesResponse } from '../../models/clinicalNotesResponse';
import type { CreatePatientRequest } from '../../models/createPatientRequest';
import type { PatientResponse } from '../../models/patientResponse';
import type { Update } from '../../models/update';
import type { UpdatePatientRequest } from '../../models/updatePatientRequest';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List patients of the office
 */
export const list1 = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<PatientResponse[]>({ url: `/api/v1/offices/${officeId}/patients`, method: 'GET', signal }, options);
};

export const getList1MutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof list1>>, TError, { officeId: string }, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof list1>>, TError, { officeId: string }, TContext> => {
  const mutationKey = ['list1'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof list1>>, { officeId: string }> = (props) => {
    const { officeId } = props ?? {};

    return list1(officeId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type List1MutationResult = NonNullable<Awaited<ReturnType<typeof list1>>>;

export type List1MutationError = unknown;

/**
 * @summary List patients of the office
 */
export const useList1 = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof list1>>, TError, { officeId: string }, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof list1>>, TError, { officeId: string }, TContext> => {
  return useMutation(getList1MutationOptions(options), queryClient);
};
/**
 * @summary Register a new patient
 */
export const create = (
  officeId: string,
  createPatientRequest: CreatePatientRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PatientResponse>(
    {
      url: `/api/v1/offices/${officeId}/patients`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createPatientRequest,
      signal,
    },
    options,
  );
};

export const getCreateQueryKey = (officeId: string, createPatientRequest?: CreatePatientRequest) => {
  return ['POST', 'api', 'v1', 'offices', officeId, 'patients', createPatientRequest] as const;
};

export const getCreateQueryOptions = <TData = Awaited<ReturnType<typeof create>>, TError = unknown>(
  officeId: string,
  createPatientRequest: CreatePatientRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getCreateQueryKey(officeId, createPatientRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof create>>> = ({ signal }) =>
    create(officeId, createPatientRequest, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type CreateQueryResult = NonNullable<Awaited<ReturnType<typeof create>>>;
export type CreateQueryError = unknown;

export function useCreate<TData = Awaited<ReturnType<typeof create>>, TError = unknown>(
  officeId: string,
  createPatientRequest: CreatePatientRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof create>>, TError, Awaited<ReturnType<typeof create>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreate<TData = Awaited<ReturnType<typeof create>>, TError = unknown>(
  officeId: string,
  createPatientRequest: CreatePatientRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof create>>, TError, Awaited<ReturnType<typeof create>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useCreate<TData = Awaited<ReturnType<typeof create>>, TError = unknown>(
  officeId: string,
  createPatientRequest: CreatePatientRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Register a new patient
 */

export function useCreate<TData = Awaited<ReturnType<typeof create>>, TError = unknown>(
  officeId: string,
  createPatientRequest: CreatePatientRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof create>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getCreateQueryOptions(officeId, createPatientRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary View a patient's registry data
 */
export const get = (
  officeId: string,
  patientId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PatientResponse>(
    { url: `/api/v1/offices/${officeId}/patients/${patientId}`, method: 'GET', signal },
    options,
  );
};

export const getGetMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof get>>,
    TError,
    { officeId: string; patientId: string },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof get>>, TError, { officeId: string; patientId: string }, TContext> => {
  const mutationKey = ['get'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof get>>, { officeId: string; patientId: string }> = (
    props,
  ) => {
    const { officeId, patientId } = props ?? {};

    return get(officeId, patientId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetMutationResult = NonNullable<Awaited<ReturnType<typeof get>>>;

export type GetMutationError = unknown;

/**
 * @summary View a patient's registry data
 */
export const useGet = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof get>>,
      TError,
      { officeId: string; patientId: string },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof get>>, TError, { officeId: string; patientId: string }, TContext> => {
  return useMutation(getGetMutationOptions(options), queryClient);
};
/**
 * @summary Update a patient's registry data
 */
export const update = (
  officeId: string,
  patientId: string,
  updatePatientRequest: UpdatePatientRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PatientResponse>(
    {
      url: `/api/v1/offices/${officeId}/patients/${patientId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updatePatientRequest,
      signal,
    },
    options,
  );
};

export const getUpdateQueryKey = (officeId: string, patientId: string, updatePatientRequest?: UpdatePatientRequest) => {
  return ['PATCH', 'api', 'v1', 'offices', officeId, 'patients', patientId, updatePatientRequest] as const;
};

export const getUpdateQueryOptions = <TData = Awaited<ReturnType<typeof update>>, TError = unknown>(
  officeId: string,
  patientId: string,
  updatePatientRequest: UpdatePatientRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUpdateQueryKey(officeId, patientId, updatePatientRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof update>>> = ({ signal }) =>
    update(officeId, patientId, updatePatientRequest, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && patientId !== null && patientId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type UpdateQueryResult = NonNullable<Awaited<ReturnType<typeof update>>>;
export type UpdateQueryError = unknown;

export function useUpdate<TData = Awaited<ReturnType<typeof update>>, TError = unknown>(
  officeId: string,
  patientId: string,
  updatePatientRequest: UpdatePatientRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof update>>, TError, Awaited<ReturnType<typeof update>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdate<TData = Awaited<ReturnType<typeof update>>, TError = unknown>(
  officeId: string,
  patientId: string,
  updatePatientRequest: UpdatePatientRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof update>>, TError, Awaited<ReturnType<typeof update>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdate<TData = Awaited<ReturnType<typeof update>>, TError = unknown>(
  officeId: string,
  patientId: string,
  updatePatientRequest: UpdatePatientRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Update a patient's registry data
 */

export function useUpdate<TData = Awaited<ReturnType<typeof update>>, TError = unknown>(
  officeId: string,
  patientId: string,
  updatePatientRequest: UpdatePatientRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof update>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUpdateQueryOptions(officeId, patientId, updatePatientRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Read the patient's clinical record
 */
export const getClinical = (
  officeId: string,
  patientId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<ClinicalNotesResponse>(
    { url: `/api/v1/offices/${officeId}/patients/${patientId}/clinical`, method: 'GET', signal },
    options,
  );
};

export const getGetClinicalMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getClinical>>,
    TError,
    { officeId: string; patientId: string },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getClinical>>,
  TError,
  { officeId: string; patientId: string },
  TContext
> => {
  const mutationKey = ['getClinical'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getClinical>>,
    { officeId: string; patientId: string }
  > = (props) => {
    const { officeId, patientId } = props ?? {};

    return getClinical(officeId, patientId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetClinicalMutationResult = NonNullable<Awaited<ReturnType<typeof getClinical>>>;

export type GetClinicalMutationError = unknown;

/**
 * @summary Read the patient's clinical record
 */
export const useGetClinical = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getClinical>>,
      TError,
      { officeId: string; patientId: string },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof getClinical>>,
  TError,
  { officeId: string; patientId: string },
  TContext
> => {
  return useMutation(getGetClinicalMutationOptions(options), queryClient);
};
/**
 * @summary Write the patient's clinical record
 */
export const updateClinical = (
  officeId: string,
  patientId: string,
  update: Update,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<ClinicalNotesResponse>(
    {
      url: `/api/v1/offices/${officeId}/patients/${patientId}/clinical`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: update,
      signal,
    },
    options,
  );
};

export const getUpdateClinicalQueryKey = (officeId: string, patientId: string, update?: Update) => {
  return ['PATCH', 'api', 'v1', 'offices', officeId, 'patients', patientId, 'clinical', update] as const;
};

export const getUpdateClinicalQueryOptions = <TData = Awaited<ReturnType<typeof updateClinical>>, TError = unknown>(
  officeId: string,
  patientId: string,
  update: Update,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateClinical>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUpdateClinicalQueryKey(officeId, patientId, update);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof updateClinical>>> = ({ signal }) =>
    updateClinical(officeId, patientId, update, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && patientId !== null && patientId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof updateClinical>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type UpdateClinicalQueryResult = NonNullable<Awaited<ReturnType<typeof updateClinical>>>;
export type UpdateClinicalQueryError = unknown;

export function useUpdateClinical<TData = Awaited<ReturnType<typeof updateClinical>>, TError = unknown>(
  officeId: string,
  patientId: string,
  update: Update,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateClinical>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateClinical>>,
          TError,
          Awaited<ReturnType<typeof updateClinical>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateClinical<TData = Awaited<ReturnType<typeof updateClinical>>, TError = unknown>(
  officeId: string,
  patientId: string,
  update: Update,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateClinical>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateClinical>>,
          TError,
          Awaited<ReturnType<typeof updateClinical>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUpdateClinical<TData = Awaited<ReturnType<typeof updateClinical>>, TError = unknown>(
  officeId: string,
  patientId: string,
  update: Update,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateClinical>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Write the patient's clinical record
 */

export function useUpdateClinical<TData = Awaited<ReturnType<typeof updateClinical>>, TError = unknown>(
  officeId: string,
  patientId: string,
  update: Update,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof updateClinical>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUpdateClinicalQueryOptions(officeId, patientId, update, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
