/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { ClinicalNotesResponse } from '../../models/clinicalNotesResponse';
import type { CreatePatientRequest } from '../../models/createPatientRequest';
import type { PatientResponse } from '../../models/patientResponse';
import type { Update } from '../../models/update';
import type { UpdatePatientRequest } from '../../models/updatePatientRequest';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary List patients of the office
 */
export const list1 = (officeId: string, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<PatientResponse[]>({ url: `/api/v1/offices/${officeId}/patients`, method: 'GET', signal }, options);
};

export const getList1QueryKey = (officeId: string) => {
  return ['api', 'v1', 'offices', officeId, 'patients'] as const;
};

export const getList1QueryOptions = <TData = Awaited<ReturnType<typeof list1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getList1QueryKey(officeId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof list1>>> = ({ signal }) =>
    list1(officeId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type List1QueryResult = NonNullable<Awaited<ReturnType<typeof list1>>>;
export type List1QueryError = unknown;

export function useList1<TData = Awaited<ReturnType<typeof list1>>, TError = unknown>(
  officeId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof list1>>, TError, Awaited<ReturnType<typeof list1>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList1<TData = Awaited<ReturnType<typeof list1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof list1>>, TError, Awaited<ReturnType<typeof list1>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useList1<TData = Awaited<ReturnType<typeof list1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List patients of the office
 */

export function useList1<TData = Awaited<ReturnType<typeof list1>>, TError = unknown>(
  officeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof list1>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getList1QueryOptions(officeId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Register a new patient
 */
export const create = (
  officeId: string,
  createPatientRequest: CreatePatientRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PatientResponse>(
    {
      url: `/api/v1/offices/${officeId}/patients`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createPatientRequest,
      signal,
    },
    options,
  );
};

export const getCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof create>>,
    TError,
    { officeId: string; data: CreatePatientRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof create>>,
  TError,
  { officeId: string; data: CreatePatientRequest },
  TContext
> => {
  const mutationKey = ['create'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof create>>,
    { officeId: string; data: CreatePatientRequest }
  > = (props) => {
    const { officeId, data } = props ?? {};

    return create(officeId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>;
export type CreateMutationBody = CreatePatientRequest;
export type CreateMutationError = unknown;

/**
 * @summary Register a new patient
 */
export const useCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof create>>,
      TError,
      { officeId: string; data: CreatePatientRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof create>>,
  TError,
  { officeId: string; data: CreatePatientRequest },
  TContext
> => {
  return useMutation(getCreateMutationOptions(options), queryClient);
};
/**
 * @summary View a patient's registry data
 */
export const get = (
  officeId: string,
  patientId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PatientResponse>(
    { url: `/api/v1/offices/${officeId}/patients/${patientId}`, method: 'GET', signal },
    options,
  );
};

export const getGetQueryKey = (officeId: string, patientId: string) => {
  return ['api', 'v1', 'offices', officeId, 'patients', patientId] as const;
};

export const getGetQueryOptions = <TData = Awaited<ReturnType<typeof get>>, TError = unknown>(
  officeId: string,
  patientId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetQueryKey(officeId, patientId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof get>>> = ({ signal }) =>
    get(officeId, patientId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && patientId !== null && patientId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetQueryResult = NonNullable<Awaited<ReturnType<typeof get>>>;
export type GetQueryError = unknown;

export function useGet<TData = Awaited<ReturnType<typeof get>>, TError = unknown>(
  officeId: string,
  patientId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof get>>, TError, Awaited<ReturnType<typeof get>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGet<TData = Awaited<ReturnType<typeof get>>, TError = unknown>(
  officeId: string,
  patientId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof get>>, TError, Awaited<ReturnType<typeof get>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGet<TData = Awaited<ReturnType<typeof get>>, TError = unknown>(
  officeId: string,
  patientId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary View a patient's registry data
 */

export function useGet<TData = Awaited<ReturnType<typeof get>>, TError = unknown>(
  officeId: string,
  patientId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof get>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetQueryOptions(officeId, patientId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Update a patient's registry data
 */
export const update = (
  officeId: string,
  patientId: string,
  updatePatientRequest: UpdatePatientRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<PatientResponse>(
    {
      url: `/api/v1/offices/${officeId}/patients/${patientId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updatePatientRequest,
      signal,
    },
    options,
  );
};

export const getUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof update>>,
    TError,
    { officeId: string; patientId: string; data: UpdatePatientRequest },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof update>>,
  TError,
  { officeId: string; patientId: string; data: UpdatePatientRequest },
  TContext
> => {
  const mutationKey = ['update'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof update>>,
    { officeId: string; patientId: string; data: UpdatePatientRequest }
  > = (props) => {
    const { officeId, patientId, data } = props ?? {};

    return update(officeId, patientId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMutationResult = NonNullable<Awaited<ReturnType<typeof update>>>;
export type UpdateMutationBody = UpdatePatientRequest;
export type UpdateMutationError = unknown;

/**
 * @summary Update a patient's registry data
 */
export const useUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof update>>,
      TError,
      { officeId: string; patientId: string; data: UpdatePatientRequest },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof update>>,
  TError,
  { officeId: string; patientId: string; data: UpdatePatientRequest },
  TContext
> => {
  return useMutation(getUpdateMutationOptions(options), queryClient);
};
/**
 * @summary Read the patient's clinical record
 */
export const getClinical = (
  officeId: string,
  patientId: string,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<ClinicalNotesResponse>(
    { url: `/api/v1/offices/${officeId}/patients/${patientId}/clinical`, method: 'GET', signal },
    options,
  );
};

export const getGetClinicalQueryKey = (officeId: string, patientId: string) => {
  return ['api', 'v1', 'offices', officeId, 'patients', patientId, 'clinical'] as const;
};

export const getGetClinicalQueryOptions = <TData = Awaited<ReturnType<typeof getClinical>>, TError = unknown>(
  officeId: string,
  patientId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinical>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetClinicalQueryKey(officeId, patientId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getClinical>>> = ({ signal }) =>
    getClinical(officeId, patientId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: officeId !== null && officeId !== undefined && patientId !== null && patientId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getClinical>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetClinicalQueryResult = NonNullable<Awaited<ReturnType<typeof getClinical>>>;
export type GetClinicalQueryError = unknown;

export function useGetClinical<TData = Awaited<ReturnType<typeof getClinical>>, TError = unknown>(
  officeId: string,
  patientId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinical>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClinical>>,
          TError,
          Awaited<ReturnType<typeof getClinical>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetClinical<TData = Awaited<ReturnType<typeof getClinical>>, TError = unknown>(
  officeId: string,
  patientId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinical>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClinical>>,
          TError,
          Awaited<ReturnType<typeof getClinical>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetClinical<TData = Awaited<ReturnType<typeof getClinical>>, TError = unknown>(
  officeId: string,
  patientId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinical>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Read the patient's clinical record
 */

export function useGetClinical<TData = Awaited<ReturnType<typeof getClinical>>, TError = unknown>(
  officeId: string,
  patientId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getClinical>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetClinicalQueryOptions(officeId, patientId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Write the patient's clinical record
 */
export const updateClinical = (
  officeId: string,
  patientId: string,
  update: Update,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<ClinicalNotesResponse>(
    {
      url: `/api/v1/offices/${officeId}/patients/${patientId}/clinical`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: update,
      signal,
    },
    options,
  );
};

export const getUpdateClinicalMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateClinical>>,
    TError,
    { officeId: string; patientId: string; data: Update },
    TContext
  >;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateClinical>>,
  TError,
  { officeId: string; patientId: string; data: Update },
  TContext
> => {
  const mutationKey = ['updateClinical'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateClinical>>,
    { officeId: string; patientId: string; data: Update }
  > = (props) => {
    const { officeId, patientId, data } = props ?? {};

    return updateClinical(officeId, patientId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateClinicalMutationResult = NonNullable<Awaited<ReturnType<typeof updateClinical>>>;
export type UpdateClinicalMutationBody = Update;
export type UpdateClinicalMutationError = unknown;

/**
 * @summary Write the patient's clinical record
 */
export const useUpdateClinical = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateClinical>>,
      TError,
      { officeId: string; patientId: string; data: Update },
      TContext
    >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateClinical>>,
  TError,
  { officeId: string; patientId: string; data: Update },
  TContext
> => {
  return useMutation(getUpdateClinicalMutationOptions(options), queryClient);
};
