/**
 * Generated by orval 🍺
 * Do not edit manually.
 * SanitasLink API
 * Identity, office (tenant) and authorization APIs. The tenant is always derived from the authenticated JWT; no X-Office-Id header is used or accepted.
 * OpenAPI spec version: v1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AcceptInvitationRequest } from '../../models/acceptInvitationRequest';
import type { ChangePasswordRequest } from '../../models/changePasswordRequest';
import type { ConfirmPasswordResetRequest } from '../../models/confirmPasswordResetRequest';
import type { LoginRequest } from '../../models/loginRequest';
import type { LoginResponse } from '../../models/loginResponse';
import type { LogoutRequest } from '../../models/logoutRequest';
import type { MeResponse } from '../../models/meResponse';
import type { RefreshTokenRequest } from '../../models/refreshTokenRequest';
import type { RequestPasswordResetRequest } from '../../models/requestPasswordResetRequest';
import { mutator } from '../../mutator';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Rotate the refresh token and obtain a new access token
 */
export const refresh = (
  refreshTokenRequest: RefreshTokenRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<LoginResponse>(
    {
      url: `/api/v1/auth/refresh`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: refreshTokenRequest,
      signal,
    },
    options,
  );
};

export const getRefreshQueryKey = (refreshTokenRequest?: RefreshTokenRequest) => {
  return ['POST', 'api', 'v1', 'auth', 'refresh', refreshTokenRequest] as const;
};

export const getRefreshQueryOptions = <TData = Awaited<ReturnType<typeof refresh>>, TError = unknown>(
  refreshTokenRequest: RefreshTokenRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRefreshQueryKey(refreshTokenRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof refresh>>> = ({ signal }) =>
    refresh(refreshTokenRequest, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof refresh>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RefreshQueryResult = NonNullable<Awaited<ReturnType<typeof refresh>>>;
export type RefreshQueryError = unknown;

export function useRefresh<TData = Awaited<ReturnType<typeof refresh>>, TError = unknown>(
  refreshTokenRequest: RefreshTokenRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof refresh>>, TError, Awaited<ReturnType<typeof refresh>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRefresh<TData = Awaited<ReturnType<typeof refresh>>, TError = unknown>(
  refreshTokenRequest: RefreshTokenRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof refresh>>, TError, Awaited<ReturnType<typeof refresh>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRefresh<TData = Awaited<ReturnType<typeof refresh>>, TError = unknown>(
  refreshTokenRequest: RefreshTokenRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Rotate the refresh token and obtain a new access token
 */

export function useRefresh<TData = Awaited<ReturnType<typeof refresh>>, TError = unknown>(
  refreshTokenRequest: RefreshTokenRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof refresh>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRefreshQueryOptions(refreshTokenRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Change the password of the authenticated user
 */
export const changePassword = (
  changePasswordRequest: ChangePasswordRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    {
      url: `/api/v1/auth/password/change`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: changePasswordRequest,
      signal,
    },
    options,
  );
};

export const getChangePasswordQueryKey = (changePasswordRequest?: ChangePasswordRequest) => {
  return ['POST', 'api', 'v1', 'auth', 'password', 'change', changePasswordRequest] as const;
};

export const getChangePasswordQueryOptions = <TData = Awaited<ReturnType<typeof changePassword>>, TError = unknown>(
  changePasswordRequest: ChangePasswordRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getChangePasswordQueryKey(changePasswordRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof changePassword>>> = ({ signal }) =>
    changePassword(changePasswordRequest, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof changePassword>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChangePasswordQueryResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>;
export type ChangePasswordQueryError = unknown;

export function useChangePassword<TData = Awaited<ReturnType<typeof changePassword>>, TError = unknown>(
  changePasswordRequest: ChangePasswordRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof changePassword>>,
          TError,
          Awaited<ReturnType<typeof changePassword>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangePassword<TData = Awaited<ReturnType<typeof changePassword>>, TError = unknown>(
  changePasswordRequest: ChangePasswordRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof changePassword>>,
          TError,
          Awaited<ReturnType<typeof changePassword>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useChangePassword<TData = Awaited<ReturnType<typeof changePassword>>, TError = unknown>(
  changePasswordRequest: ChangePasswordRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Change the password of the authenticated user
 */

export function useChangePassword<TData = Awaited<ReturnType<typeof changePassword>>, TError = unknown>(
  changePasswordRequest: ChangePasswordRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof changePassword>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getChangePasswordQueryOptions(changePasswordRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Request a password reset (uniform response, no account enumeration)
 */
export const requestPasswordReset = (
  requestPasswordResetRequest: RequestPasswordResetRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    {
      url: `/api/v1/auth/password-reset/request`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: requestPasswordResetRequest,
      signal,
    },
    options,
  );
};

export const getRequestPasswordResetQueryKey = (requestPasswordResetRequest?: RequestPasswordResetRequest) => {
  return ['POST', 'api', 'v1', 'auth', 'password-reset', 'request', requestPasswordResetRequest] as const;
};

export const getRequestPasswordResetQueryOptions = <
  TData = Awaited<ReturnType<typeof requestPasswordReset>>,
  TError = unknown,
>(
  requestPasswordResetRequest: RequestPasswordResetRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRequestPasswordResetQueryKey(requestPasswordResetRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof requestPasswordReset>>> = ({ signal }) =>
    requestPasswordReset(requestPasswordResetRequest, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof requestPasswordReset>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RequestPasswordResetQueryResult = NonNullable<Awaited<ReturnType<typeof requestPasswordReset>>>;
export type RequestPasswordResetQueryError = unknown;

export function useRequestPasswordReset<TData = Awaited<ReturnType<typeof requestPasswordReset>>, TError = unknown>(
  requestPasswordResetRequest: RequestPasswordResetRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof requestPasswordReset>>,
          TError,
          Awaited<ReturnType<typeof requestPasswordReset>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRequestPasswordReset<TData = Awaited<ReturnType<typeof requestPasswordReset>>, TError = unknown>(
  requestPasswordResetRequest: RequestPasswordResetRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof requestPasswordReset>>,
          TError,
          Awaited<ReturnType<typeof requestPasswordReset>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRequestPasswordReset<TData = Awaited<ReturnType<typeof requestPasswordReset>>, TError = unknown>(
  requestPasswordResetRequest: RequestPasswordResetRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Request a password reset (uniform response, no account enumeration)
 */

export function useRequestPasswordReset<TData = Awaited<ReturnType<typeof requestPasswordReset>>, TError = unknown>(
  requestPasswordResetRequest: RequestPasswordResetRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof requestPasswordReset>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRequestPasswordResetQueryOptions(requestPasswordResetRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Confirm a password reset with the one-time token
 */
export const confirmPasswordReset = (
  confirmPasswordResetRequest: ConfirmPasswordResetRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    {
      url: `/api/v1/auth/password-reset/confirm`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: confirmPasswordResetRequest,
      signal,
    },
    options,
  );
};

export const getConfirmPasswordResetQueryKey = (confirmPasswordResetRequest?: ConfirmPasswordResetRequest) => {
  return ['POST', 'api', 'v1', 'auth', 'password-reset', 'confirm', confirmPasswordResetRequest] as const;
};

export const getConfirmPasswordResetQueryOptions = <
  TData = Awaited<ReturnType<typeof confirmPasswordReset>>,
  TError = unknown,
>(
  confirmPasswordResetRequest: ConfirmPasswordResetRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof confirmPasswordReset>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getConfirmPasswordResetQueryKey(confirmPasswordResetRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof confirmPasswordReset>>> = ({ signal }) =>
    confirmPasswordReset(confirmPasswordResetRequest, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof confirmPasswordReset>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ConfirmPasswordResetQueryResult = NonNullable<Awaited<ReturnType<typeof confirmPasswordReset>>>;
export type ConfirmPasswordResetQueryError = unknown;

export function useConfirmPasswordReset<TData = Awaited<ReturnType<typeof confirmPasswordReset>>, TError = unknown>(
  confirmPasswordResetRequest: ConfirmPasswordResetRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof confirmPasswordReset>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof confirmPasswordReset>>,
          TError,
          Awaited<ReturnType<typeof confirmPasswordReset>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useConfirmPasswordReset<TData = Awaited<ReturnType<typeof confirmPasswordReset>>, TError = unknown>(
  confirmPasswordResetRequest: ConfirmPasswordResetRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof confirmPasswordReset>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof confirmPasswordReset>>,
          TError,
          Awaited<ReturnType<typeof confirmPasswordReset>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useConfirmPasswordReset<TData = Awaited<ReturnType<typeof confirmPasswordReset>>, TError = unknown>(
  confirmPasswordResetRequest: ConfirmPasswordResetRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof confirmPasswordReset>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Confirm a password reset with the one-time token
 */

export function useConfirmPasswordReset<TData = Awaited<ReturnType<typeof confirmPasswordReset>>, TError = unknown>(
  confirmPasswordResetRequest: ConfirmPasswordResetRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof confirmPasswordReset>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getConfirmPasswordResetQueryOptions(confirmPasswordResetRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Revoke the provided refresh token
 */
export const logout = (
  logoutRequest: LogoutRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<void>(
    {
      url: `/api/v1/auth/logout`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: logoutRequest,
      signal,
    },
    options,
  );
};

export const getLogoutQueryKey = (logoutRequest?: LogoutRequest) => {
  return ['POST', 'api', 'v1', 'auth', 'logout', logoutRequest] as const;
};

export const getLogoutQueryOptions = <TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
  logoutRequest: LogoutRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLogoutQueryKey(logoutRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof logout>>> = ({ signal }) =>
    logout(logoutRequest, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type LogoutQueryResult = NonNullable<Awaited<ReturnType<typeof logout>>>;
export type LogoutQueryError = unknown;

export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
  logoutRequest: LogoutRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof logout>>, TError, Awaited<ReturnType<typeof logout>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
  logoutRequest: LogoutRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof logout>>, TError, Awaited<ReturnType<typeof logout>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
  logoutRequest: LogoutRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Revoke the provided refresh token
 */

export function useLogout<TData = Awaited<ReturnType<typeof logout>>, TError = unknown>(
  logoutRequest: LogoutRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof logout>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getLogoutQueryOptions(logoutRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Login and obtain tokens
 */
export const login = (loginRequest: LoginRequest, options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<LoginResponse>(
    {
      url: `/api/v1/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginRequest,
      signal,
    },
    options,
  );
};

export const getLoginQueryKey = (loginRequest?: LoginRequest) => {
  return ['POST', 'api', 'v1', 'auth', 'login', loginRequest] as const;
};

export const getLoginQueryOptions = <TData = Awaited<ReturnType<typeof login>>, TError = unknown>(
  loginRequest: LoginRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLoginQueryKey(loginRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof login>>> = ({ signal }) =>
    login(loginRequest, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type LoginQueryResult = NonNullable<Awaited<ReturnType<typeof login>>>;
export type LoginQueryError = unknown;

export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = unknown>(
  loginRequest: LoginRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof login>>, TError, Awaited<ReturnType<typeof login>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = unknown>(
  loginRequest: LoginRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof login>>, TError, Awaited<ReturnType<typeof login>>>,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = unknown>(
  loginRequest: LoginRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Login and obtain tokens
 */

export function useLogin<TData = Awaited<ReturnType<typeof login>>, TError = unknown>(
  loginRequest: LoginRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof login>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getLoginQueryOptions(loginRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Accept an office invitation and set the first-access password
 */
export const acceptInvitation = (
  acceptInvitationRequest: AcceptInvitationRequest,
  options?: SecondParameter<typeof mutator>,
  signal?: AbortSignal,
) => {
  return mutator<LoginResponse>(
    {
      url: `/api/v1/auth/invitations/accept`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: acceptInvitationRequest,
      signal,
    },
    options,
  );
};

export const getAcceptInvitationQueryKey = (acceptInvitationRequest?: AcceptInvitationRequest) => {
  return ['POST', 'api', 'v1', 'auth', 'invitations', 'accept', acceptInvitationRequest] as const;
};

export const getAcceptInvitationQueryOptions = <TData = Awaited<ReturnType<typeof acceptInvitation>>, TError = unknown>(
  acceptInvitationRequest: AcceptInvitationRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof acceptInvitation>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAcceptInvitationQueryKey(acceptInvitationRequest);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof acceptInvitation>>> = ({ signal }) =>
    acceptInvitation(acceptInvitationRequest, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof acceptInvitation>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AcceptInvitationQueryResult = NonNullable<Awaited<ReturnType<typeof acceptInvitation>>>;
export type AcceptInvitationQueryError = unknown;

export function useAcceptInvitation<TData = Awaited<ReturnType<typeof acceptInvitation>>, TError = unknown>(
  acceptInvitationRequest: AcceptInvitationRequest,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof acceptInvitation>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof acceptInvitation>>,
          TError,
          Awaited<ReturnType<typeof acceptInvitation>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAcceptInvitation<TData = Awaited<ReturnType<typeof acceptInvitation>>, TError = unknown>(
  acceptInvitationRequest: AcceptInvitationRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof acceptInvitation>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof acceptInvitation>>,
          TError,
          Awaited<ReturnType<typeof acceptInvitation>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAcceptInvitation<TData = Awaited<ReturnType<typeof acceptInvitation>>, TError = unknown>(
  acceptInvitationRequest: AcceptInvitationRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof acceptInvitation>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Accept an office invitation and set the first-access password
 */

export function useAcceptInvitation<TData = Awaited<ReturnType<typeof acceptInvitation>>, TError = unknown>(
  acceptInvitationRequest: AcceptInvitationRequest,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof acceptInvitation>>, TError, TData>>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAcceptInvitationQueryOptions(acceptInvitationRequest, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Current user profile with effective roles and permissions
 */
export const me = (options?: SecondParameter<typeof mutator>, signal?: AbortSignal) => {
  return mutator<MeResponse>({ url: `/api/v1/auth/me`, method: 'GET', signal }, options);
};

export const getMeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof me>>, TError, void, TContext>;
  request?: SecondParameter<typeof mutator>;
}): UseMutationOptions<Awaited<ReturnType<typeof me>>, TError, void, TContext> => {
  const mutationKey = ['me'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof me>>, void> = () => {
    return me(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MeMutationResult = NonNullable<Awaited<ReturnType<typeof me>>>;

export type MeMutationError = unknown;

/**
 * @summary Current user profile with effective roles and permissions
 */
export const useMe = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof me>>, TError, void, TContext>;
    request?: SecondParameter<typeof mutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof me>>, TError, void, TContext> => {
  return useMutation(getMeMutationOptions(options), queryClient);
};
